name: C++ Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build tests
        run: g++ Student.cpp test.cpp -o tests

      - name: Run tests
        run: ./tests
